name: Fetch upstream Action(rebase)
description: Syncs and rebase your current repository with the upstream repository.
author: tjusl

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo 
    required: true
  upstream_branch:
    description: repo branch to fetch
    required: true
  local_branch:
    description: local repo branch
    required: true
  github_token:
    description: github push token
    required: true
  git_clone_depth:
    description: git clone depth for working target repo
    required: false
    default: 100
  git_fetch_depth:
    description: git fetch depth for target upstream repo
    required: false
    default: 100

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.local_branch }}
    - ${{ inputs.github_token }}
    - ${{ inputs.git_clone_depth }}
    - ${{ inputs.git_fetch_depth }}


branding:
  icon: 'git-merge'
  color: 'blue'
